# Generated by Django 3.2.4 on 2021-06-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('photo', models.ImageField(upload_to='photo')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
