# Generated by Django 3.2.4 on 2021-06-16 13:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0004_auto_20210616_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='link',
        ),
        migrations.RemoveField(
            model_name='question',
            name='photo',
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
