# Generated by Django 3.2.4 on 2021-06-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0006_auto_20210617_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='placement',
            field=models.PositiveIntegerField(),
        ),
    ]
