# Generated by Django 3.2.4 on 2021-06-23 12:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FAQ', '0007_alter_question_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_bg',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
