# Generated by Django 3.2.4 on 2021-06-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210616_1341'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
