# Generated by Django 3.2.4 on 2021-06-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20210617_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adress',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
