# Generated by Django 3.2.4 on 2021-06-16 14:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('upload', models.FileField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('meta_description', models.TextField(default=None)),
                ('meta_keywords', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
