# Generated by Django 3.2.4 on 2021-06-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0003_auto_20210618_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='slug',
            field=models.SlugField(default='about-us'),
        ),
    ]
