# Generated by Django 3.2.4 on 2021-06-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0004_aboutus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='position',
            field=models.CharField(choices=[('home', 'Home'), ('footer', 'Footer')], max_length=20),
        ),
    ]
