# Generated by Django 3.2.4 on 2021-06-23 12:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0005_alter_textpage_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='description_bg',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='description_bg',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='title_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
