# Generated by Django 3.2.4 on 2021-06-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0006_auto_20210623_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpage',
            name='meta_description_bg',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='meta_description_en',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='meta_keywords_bg',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textpage',
            name='meta_keywords_en',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
