# Generated by Django 3.2.4 on 2021-06-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0007_auto_20210624_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('home', 'Home'), ('contact', 'Contacts'), ('companies', 'Companies'), ('about-us', 'About us'), ('faq', 'FAQ'), ('external-links', 'External Links')], max_length=100)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
