# Generated by Django 3.2.4 on 2021-06-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0009_rename_display_order_navbar_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='position',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
