# Generated by Django 3.2.4 on 2021-06-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0010_alter_navbar_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbar',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='textpage',
            name='upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
