# Generated by Django 3.2.4 on 2021-06-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0011_auto_20210625_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
