# Generated by Django 3.2.4 on 2021-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0012_alter_navbar_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='name_bg',
            field=models.CharField(choices=[('home', 'Home'), ('contact', 'Contacts'), ('companies', 'Companies'), ('about-us', 'About us'), ('faq', 'FAQ'), ('external-links', 'External Links')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='name_en',
            field=models.CharField(choices=[('home', 'Home'), ('contact', 'Contacts'), ('companies', 'Companies'), ('about-us', 'About us'), ('faq', 'FAQ'), ('external-links', 'External Links')], max_length=100, null=True),
        ),
    ]
