# Generated by Django 3.2.4 on 2021-06-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_pages', '0014_auto_20210625_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textpage',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
