# Generated by Django 3.2.4 on 2021-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20210616_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={},
        ),
        migrations.RemoveField(
            model_name='companies',
            name='placement',
        ),
    ]
