# Generated by Django 3.2.4 on 2021-06-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('companies', '0004_auto_20210616_1244'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Companie',
        ),
        migrations.RenameModel(
            old_name='Politics',
            new_name='Politic',
        ),
    ]
