# Generated by Django 3.2.4 on 2021-06-16 13:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20210616_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politic',
            name='upload',
        ),
        migrations.AlterField(
            model_name='politic',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
