# Generated by Django 3.2.4 on 2021-06-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20210617_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='politic',
            name='file',
            field=models.FileField(default=None, upload_to='uploads/files'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companie',
            name='main_image',
            field=models.ImageField(upload_to='uploads/images'),
        ),
    ]
