# Generated by Django 3.2.4 on 2021-06-23 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20210623_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='politic',
            name='description_bg',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='politic',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='politic',
            name='title_bg',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='politic',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
