# Generated by Django 3.2.4 on 2021-06-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_auto_20210623_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companie',
            name='placement',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
