# Generated by Django 3.2.4 on 2021-06-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallinks',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
