# Generated by Django 3.2.4 on 2021-06-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0002_externallinks_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalLinks',
            new_name='ExternalLink',
        ),
    ]
