# Generated by Django 3.2.4 on 2021-06-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('external_links', '0003_rename_externallinks_externallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='externallink',
            name='description_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='externallink',
            name='description_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='externallink',
            name='title_bg',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='externallink',
            name='title_en',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
